### ISSUE TITLE
sending email not working

### ISSUE THREAD

**Issue by dtbu** [bpodwinski/docker-phpservermon#2]
Hello,
your dockerimage ist working well, but i had a problem with setting an sending emails.
When i configure email settings and will test them, the browser receive a http 500 error. With debug mode enabled i see an error message from phpservermonitor like https://github.com/phpservermon/phpservermon/issues/598 .

I have fixed this error with the following changes:
+++
var/www/src/includes # diff functions.inc.php.org  functions.inc.php
--- functions.inc.php.org
+++ functions.inc.php
@@ -486,7 +486,8 @@
  * @return \PHPMailer
  */
 function psm_build_mail($from_name = null, $from_email = null) {
-       $phpmailer = new \PHPMailer();
+       $phpmailer = new \PHPMailer\PHPMailer\PHPMailer();
+       //$phpmailer = new \PHPMailer();
        $phpmailer->Encoding = "base64";
        $phpmailer->CharSet = 'UTF-8';
        $phpmailer->SMTPDebug = false;
+++
Please fix this in a new version of your dockerimage.
Thank you very much.
regards,
Dirk

**Comment by bpodwinski** [comment]
It's ok, I have updated my docker image.

Benoit.

**Comment by dtbu** [comment]
Great, it works! Thanks for fixing this issue.
Dirk
