### ISSUE TITLE
pinging via manual update fails

### ISSUE THREAD

**Issue by berkutta** [bpodwinski/docker-phpservermon#3]
If I try to Update manually through the "Update" Button in the UI all "Ping" hosts fail with following error:
`Couldn't create socket [1]: Operation not permitted`

The normal check loop runs fine. I'm not sure if it's a permission issue because the normal loop runs on root.

**Comment by bpodwinski** [comment]
Fixed: replace user & group www-data to root for php-fpm c4fd77fa068b7c56b3335368a7f013965222fd11
